### PR TITLE
Fix issue with multiple titles

### PR DESCRIPTION
**Pull request by paulo-graca**
fixing issue with multiple titles

### CODE REVIEW

**Comment by paulo-graca** [comment]
hi @lmatas, I think it was an initial test. I left the identifier field as it was, but use the same PR to address an issue occurred with multiple titles. Can you review it please?

**Comment by lareferencia** [comment]
<xsl:template match="doc:element[@name='titles']/doc:element[@name='title'][1]" mode="datacite">	
It should be [0] or it begins in 1??
No sure, just asking

**Comment by paulo-graca** [comment]
It's for the first position. It's transformed into:

image

**Comment by lareferencia** [comment]
Ok. I am promoting this change to master

**Pull request merged**
